name: Setup Amber Compiler
description: Download an Amber compiler.
branding:
  color: orange
  icon: download
inputs:
  amber-version:
    description: The version of Amber to install.
    default: 0.5.1-alpha
  enable-cache:
    description: Whether to cache Amber binaries.
    default: true
  cache-path:
    description: >-
      The path to directory where Amber binary caches are stored.
      If empty string is given, the used path depends on the runner.
    default: ""
  bin-path:
    description: >-
      The path to location where the final amber binary should be located.
      Default to `/usr/local/bin/amber`.
    default: /usr/local/bin/amber
runs:
  using: node24
  main: dist/index.js
  post: dist/index.js
