name: Setup Amber Compiler
description: Download an Amber compiler.
branding:
  color: orange
  icon: download
inputs:
  amber-version:
    description: The version of Amber to install.
    default: 0.5.1-alpha
  enable-cache:
    description: Whether to cache Amber binaries.
    default: true
  cache-path:
    description: >-
      The path to directory where Amber binary caches are stored.
      If empty string is given, defaults to ~/.tools on the runner.
    default: ""
  bin-path:
    description: >-
      The path to location where the final amber binary should be located.
      Default to `/usr/local/bin/amber`.
    default: /usr/local/bin/amber
outputs:
  amber-path:
    description: The path where the Amber binary was installed.
    value: ${{ steps.main.outputs.amber-path }}
runs:
  using: composite
  steps:
    - shell: bash
      env:
        INPUT_CACHE_PATH: ${{ inputs.cache-path }}
      id: cache-path
      run: |
        # Handle user-given cache-path
        delimiter="ghadelimiter_$(openssl rand -hex 16)"
        cache_path="${INPUT_CACHE_PATH:-$HOME/.tools}"
        {
          echo "amber_cache_path<<$delimiter"
          echo "$cache_path"
          echo "$delimiter"
        } >> "$GITHUB_OUTPUT"
    - name: Cache Amber binaries
      uses: actions/cache@9255dc7a253b0ccc959486e2bca901246202afeb # v5.0.1
      if: inputs.enable-cache
      with:
        path: ${{ steps.cache-path.outputs.amber_cache_path }}/amber
        key: setup-amber-${{ runner.os }}-${{ runner.arch }}-${{ inputs.amber-version }}
    - id: main
      shell: bash
      env:
        SETUP_AMBER_CACHE_PATH: ${{ env.amber_cache_path }}
        SETUP_AMBER_BIN_PATH: ${{ inputs.bin-path }}
        SETUP_AMBER_VERSION: ${{ inputs.amber-version }}
      run: |
        # Download Amber binary
        bash "${{ github.action_path }}/dist/main.sh"
